site_name: BCE
theme: 
  name: flatly
  custom_dir: docs/assets/

nav:
    - Inicial: index.md
    - Planejamento:
      - Planejamento projeto: planejamento_projeto.md
      - Metodologia: metodologia_do_projeto.md
      - Escolha do site: escolha_site.md